# Generated by Django 4.2.10 on 2024-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(default='1900-01-01', verbose_name='Date of Birth'),
        ),
    ]
