# Generated by Django 4.2.10 on 2024-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Unspecified', 'Prefer not to say'), ('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=12, verbose_name='Gender'),
        ),
    ]
